#!/bin/sh

if test $# -eq 0
then
./bin/card6_asmpp ./asm/card6vm.s asm.s
java -jar jar/card6_asm.jar asm.s a.out
rm asm.s
echo "assemble end"
exit 0
fi

if test $# -gt 0
then
./bin/card6_asmpp ./asm/card6vm.s asm.s
java -jar jar/card6_asm.jar -list asm.s a.out > $1
rm asm.s
echo "assemble end"
exit 0
fi
